### ISSUE TITLE
Error when reproduce dailydialog dataset 

### ISSUE THREAD

**Issue by xiang-xiang-zhu** [caoyu-noob/embedding_augmentation#3]
```
Traceback (most recent call last):
  File "train.py", line 301, in <module>
    main()
  File "train.py", line 298, in main
    last_checkpoint_path, interrupt_checkpoint_path, log_dir, test_data_type=args.test_data_type)
  File "train.py", line 144, in training_procedure
    pointer_gen=args.pointer_gen)
  File "/home/hx/github项目/embedding_augmentation/model/trainer.py", line 97, in __init__
    train_sampler = RandomSampler(train_dataset)
  File "/home/hx/anaconda3/envs/torch1.4/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 103, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0
```
I print the len(train_dataset) ,and its value is 0
Is the data process code wrong?

**Comment by caoyu-noob** [comment]
Could you tell me more about your settings? Which dataset is used in your training? It seems that there is an empty dataset loaded. 
Did you try the shell "train_summy.sh"? Is everything OK?

**Comment by xiang-xiang-zhu** [comment]
> Could you tell me more about your settings? Which dataset is used in your training? It seems that there is an empty dataset loaded. Did you try the shell "train_summy.sh"? Is everything OK?

@caoyu-noob  I download the daily dataset in the [website](http://yanran.li/dailydialog),and i unzip it get the ijcnlp_dailydailog folder,it with three .zip file(train,validation,test.zip).I unzip them and get three folders,each includes dialogues_{split}.txt, 
    dialogues_emotion_{spilt}.txt    and     dialogues_act_{split}.txt.
I put them in the dataset folder.
And it's my train_dailydialog.sh
```
CUDA_VISIBLE_DEVICES=0 python train.py \
--train_batch_size 256 \
--batch_split 8 \
--n_epochs 50 \
--lr 2e-4 \
--train_datasets datasets/ijcnlp_dailydialog/train/dialogues_train.txt \
--valid_datasets datasets/ijcnlp_dailydialog/validation/dialogues_validation.txt \
--test_datasets datasets/ijcnlp_dailydialog/test/dialogues_test.txt \
--train_datasets_cache datasets/ijcnlp_dailydialog/dailydialog_train_seq2seq_cache \
--valid_datasets_cache datasets/ijcnlp_dailydialog/dailydialog_valid_seq2seq_cache \
--test_datasets_cache datasets/ijcnlp_dailydialog/dailydialog_test_seq2seq_cache \
--vocab_path datasets/vocab/dailydialog_vocab.bin \
--data_type daily \
--model_type seq2seq \
--pointer_gen \
--s2s_weight 1 \
--max_history_size 5 \
--mixup \
--mixup_model_path ./fasttext_model/dailogdialog_50_cbow.bin \
--mixup_ratio 0.4 \
--mixup_cache datasets/ijcnlp_dailydialog/mixup_cache_seq2seq_th0.4 \
--mixup_candidate_th 0.4 \
--mixup_soft_loss_weight 1
```
When i run this, the error occurs.
I can run successfully on  PersonaChat dataset with the  train_both_original.txt througn train_persona.sh. So there should be no problem with the code. Maybe the format of the dailydialog dataset needs to be processed ?

I also try use the [parser.py](https://github.com/Sanghoon94/DailyDialogue-Parser) to process the data,and get three dial.txt file.
Unfortunately, the same mistake will still happen.
Thanks.

**Comment by xiang-xiang-zhu** [comment]
Is there any solution?

**Comment by caoyu-noob** [comment]
I have already updated the repo about two weeks ago, and there are some new description about how to pre-processing the DailyDialog dataset. I also left a comment at that time. But it is very strange that this comment disappears.

**Comment by xiang-xiang-zhu** [comment]
> I have already updated the repo about two weeks ago, and there are some new description about how to pre-processing the DailyDialog dataset. I also left a comment at that time. But it is very strange that this comment disappears.

It work !
Thanks
